Fix: Display name webhook fail fix
countr/countr pull request #1285
Opened 2024-07-18 21:09 UTC by JayyDoesDev

Instead of failing on names like "everyone" or "here" since Discord blocks these, it will default back to the user's username.

2024-09-01 18:12 UTC, djohts reviewed
FYI relying on `member.user.displayName` is safe here as Discord prohibits `everyone` and `here` in display names. No idea why they don't do that for server display names though.
![image](https://github.com/user-attachments/assets/027e4893-1a1a-41f3-877e-8fc80d2d9a5d)

2024-09-02 00:10 UTC, JayyDoesDev reviewed
This code is incorrect. Your code will always return false given the array doesn't directly check anything regarding the name. Your code only checks the array of rather it has a displayName or not.

2024-09-03 09:23 UTC, promise requested changes

2024-09-03 09:23 UTC, promise commented on src/handlers/counting/repost/webhook.ts
> +    username: ["everyone", "here"].includes(member.displayName) ? member.user.displayName : member.displayName,
uppercase everyone or here names will bypass this filter

2024-09-03 16:10 UTC, merged