implements #143
countr/countr pull request #209
Opened 2022-03-17 22:44 UTC by wrac4242

implements #143 to add a greater than or equal to trigger

2022-03-17 22:52 UTC, promise requested changes

2022-03-17 22:52 UTC, promise commented on src/constants/triggers.ts
> +    check: ({ count }, [[number]]: Array<Array<number>>) => Promise.resolve(typeof count === typeof number && count >= number),
both variables will always be number so this type check is not needed

2022-03-17 22:52 UTC, promise commented on src/constants/triggers.ts
> +    explanation: ([[number]]: Array<Array<number>>) => `When someone counts the number ${number} or more`,
explanation can rather be something like `When someone counts a number greater than or equal to ${number}, for example ${number}, ${number + 1}, ${number + 2} and so on.`

2022-03-18 05:27 UTC, wrac4242 commented
changes have been resolved

2022-03-18 05:53 UTC, promise approved these changes
lgtm! ty 😃

2022-03-18 05:53 UTC, merged