Add position roles
countr/countr pull request #471
Opened 2022-09-23 08:09 UTC by promise

Fixes #94

2022-09-23 10:51 UTC, Ta1al commented on src/commands/chatInput/positionroles/set.ts
> +      required: true,
`minValue` & `maxValue` can be added here

2022-09-23 11:03 UTC, Ta1al requested changes
There is currently no way to remove the position roles.

2022-09-23 11:03 UTC, Ta1al commented on src/commands/chatInput/positionroles/set.ts
> +    if (position < 1 || position > limits.positionRole.max) {
This check isn't needed if `minValue` & `maxValue` in the interaction option

2022-09-23 11:11 UTC, promise commented
will work on removing position roles soon, but pls review current changes

2022-09-23 11:12 UTC, Ta1al approved these changes

2022-09-29 10:14 UTC, itzJOHv approved these changes

2022-09-30 07:25 UTC, Ta1al requested changes

2022-09-30 07:25 UTC, Ta1al commented on src/commands/chatInput/positionroles/list.ts
> +          content: `💢 Are you sure you want to delete position roles for position${positions.length === 1 ? "" : "s"} ${formatListToHuman(positions)}?`,
For grammar's sake, at a plural check for **roles** as well.

2022-10-01 09:58 UTC, Ta1al approved these changes

2022-10-13 07:15 UTC, merged