Flow additions (Fix #88)
countr/countr pull request #92
Opened 2021-03-18 17:44 UTC by promise

This is untested, will test tomorrow. If reviewers wants to test and make sure it works then that is also fine by me.

2021-03-19 03:00 UTC, e5510 approved these changes
Everything seems fine to me except #93 , seems to run fine on windows 10.

2021-03-19 10:40 UTC, thefabicraft-github approved these changes

2021-03-20 01:57 UTC, Ta1al requested changes
It would be better if a message was sent in to chat that the count has been reset because someone counted incorrectly or because of some other trigger.

2021-03-20 10:14 UTC, promise commented
> It would be better if a message was sent in to chat that the count has been reset because someone counted incorrectly or because of some other trigger.

The server admins can use the message action then. Up to them if they want to send a message or not.

2021-03-20 12:24 UTC, Aditya20-ai approved these changes

2021-03-21 03:53 UTC, Ta1al approved these changes

2021-03-21 09:39 UTC, merged